// <auto-generated />
using MercanlarApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MercanlarApi.Migrations
{
    [DbContext(typeof(MercanDB))]
    [Migration("20241022103920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("MercanlarApi.Model.AracModel", b =>
                {
                    b.Property<string>("Plaka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Per")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sofor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sube")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Plaka");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("MercanlarApi.Model.KargoModel", b =>
                {
                    b.Property<string>("CariNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evrak")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tarih")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Teslim_Alan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Teslim_Tarihi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CariNo");

                    b.ToTable("Kargolar");
                });
#pragma warning restore 612, 618
        }
    }
}
